// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xiebxzendzyjfpejglxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpZWJ4emVuZHp5amZwZWpnbHhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0OTU0MTQsImV4cCI6MjA2ODA3MTQxNH0.ZPINJbb2jP-T2M5HLtxTinKfTEkJ4wuSBYn7UkOHlqE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});